server:
  port: 9999
  servlet:
    context-path: /bizAcct
spring:
  application:
    name: bizAcct
  profiles:
    active: dev
  mvc:
    view:
      prefix: /html/
      suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/
  rabbitmq:
    virtual-host: workflow
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 30
        prefetch: 3
rabbit:
  queue:
    eod: bizacct_eod
    
    
    


