server:
  port: 9999
  servlet:
    context-path: /workflow
spring:
  application:
    name: workflow
  profiles:
    active: dev
  rabbitmq:
    virtual-host: workflow
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 30
        prefetch: 10
  datasource:
    username: root
    password: d2p9bupt
    url: jdbc:mysql://localhost:3306/workflow
    driver-class-name: com.mysql.jdbc.Driver
rabbit:
  queue:
    flow: workflow_zk
